cuda
2022-11-19 07:41:31,824 - root - INFO - Task Started
2022-11-19 07:41:31,824 - root - INFO - [1/1] Data Preparing - Start
Traceback (most recent call last):
  File "/opt/ml/input/code/lightgcn/train.py", line 63, in <module>
    main()
  File "/opt/ml/input/code/lightgcn/train.py", line 50, in main
    valid_data=valid_data,
NameError: name 'valid_data' is not defined
2022-11-19 07:41:43,574 - data - INFO - Train Dataset Info
2022-11-19 07:41:43,575 - data - INFO -  * Num. Users    : 7442
2022-11-19 07:41:43,575 - data - INFO -  * Max. UserID   : 7441
2022-11-19 07:41:43,575 - data - INFO -  * Num. Items    : 9454
2022-11-19 07:41:43,576 - data - INFO -  * Num. Records  : 2475230
2022-11-19 07:41:43,576 - data - INFO - Test Dataset Info
2022-11-19 07:41:43,577 - data - INFO -  * Num. Users    : 744
2022-11-19 07:41:43,577 - data - INFO -  * Max. UserID   : 7439
2022-11-19 07:41:43,577 - data - INFO -  * Num. Items    : 452
2022-11-19 07:41:43,577 - data - INFO -  * Num. Records  : 744
2022-11-19 07:41:43,670 - root - INFO - [1/1] Data Preparing - Done
2022-11-19 07:41:43,671 - root - INFO - [2/2] Model Building - Start
2022-11-19 07:41:43,681 - build - INFO - No load model
2022-11-19 07:41:43,683 - root - INFO - [2/2] Model Building - Done
2022-11-19 07:41:43,683 - root - INFO - [3/3] Model Training - Start