cuda
2022-11-19 07:45:15,562 - root - INFO - Task Started
2022-11-19 07:45:15,562 - root - INFO - [1/1] Data Preparing - Start
Traceback (most recent call last):
  File "/opt/ml/input/code/lightgcn/train.py", line 63, in <module>
    main()
  File "/opt/ml/input/code/lightgcn/train.py", line 24, in main
    train_data, test_data, n_node = prepare_dataset(
  File "/opt/ml/input/code/lightgcn/lightgcn/datasets.py", line 17, in prepare_dataset
    x_train, x_valid, y_train, y_valid = train_test_split(train_data_proc['edge'], train_data_proc['label'], test_size=0.2, random_state=42)
  File "/opt/conda/envs/lgcn/lib/python3.10/site-packages/sklearn/model_selection/_split.py", line 2445, in train_test_split
    arrays = indexable(*arrays)
  File "/opt/conda/envs/lgcn/lib/python3.10/site-packages/sklearn/utils/validation.py", line 433, in indexable
    check_consistent_length(*result)
  File "/opt/conda/envs/lgcn/lib/python3.10/site-packages/sklearn/utils/validation.py", line 387, in check_consistent_length
    raise ValueError(
ValueError: Found input variables with inconsistent numbers of samples: [2, 2475230]